In [1]:
import pandas as pd

df = pd.read_csv("../data/iris.csv")

In [2]:
df_clean = df.copy()

In [3]:
df_clean["sepal_area"] = (
    df_clean["sepal_length"]
    * df_clean["sepal_width"]
)

In [4]:
df_clean.head()

   sepal_length  sepal_width  petal_length  petal_width species  sepal_area
0           5.1          3.5           1.4          0.2  setosa       17.85
1           4.9          3.0           1.4          0.2  setosa       14.70
2           4.7          3.2           1.3          0.2  setosa       15.04
3           4.6          3.1           1.5          0.2  setosa       14.26
4           5.0          3.6           1.4          0.2  setosa       18.00

In [4]:
df_clean.to_csv(
    "../data/iris_clean.csv",
    index=False
)

In [5]:
df_clean.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
sepal_area      0
dtype: int64

In [6]:
df_clean.duplicated().sum()

np.int64(1)

In [7]:
print("Rows:", len(df_clean))
print("Missing values:")
print(df_clean.isnull().sum())

print("Duplicate rows:")
print(df_clean.duplicated().sum())

Rows: 150
Missing values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
sepal_area      0
dtype: int64
Duplicate rows:
1

In [8]:
df_clean["petal_area"] = df_clean["petal_length"] * df_clean["petal_width"]

In [12]:
df_clean.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area,petal_area
0,5.1,3.5,1.4,0.2,setosa,17.85,0.28
1,4.9,3.0,1.4,0.2,setosa,14.70,0.28
2,4.7,3.2,1.3,0.2,setosa,15.04,0.26
3,4.6,3.1,1.5,0.2,setosa,14.26,0.30
4,5.0,3.6,1.4,0.2,setosa,18.00,0.28

In [9]:
df_clean.to_csv(
    "../data/iris_clean.csv",
    index=False
)

In [10]:
df_clean["petal_to_sepal_ratio"] = ( 
    df_clean["petal_area"] / df_clean["sepal_area"]
    )

In [11]:
df_clean.describe()

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area,petal_to_sepal_ratio
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,17.822867,5.794067,0.314798
std,0.828066,0.435866,1.765298,0.762238,3.361854,4.712390,0.235942
min,4.300000,2.000000,1.000000,0.100000,10.000000,0.110000,0.007036
25%,5.100000,2.800000,1.600000,0.300000,15.660000,0.420000,0.023640
50%,5.800000,3.000000,4.350000,1.300000,17.660000,5.615000,0.336696
75%,6.400000,3.300000,5.100000,1.800000,20.325000,9.690000,0.515812
max,7.900000,4.400000,6.900000,2.500000,30.020000,15.870000,0.792707

In [12]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sepal_length          150 non-null    float64
 1   sepal_width           150 non-null    float64
 2   petal_length          150 non-null    float64
 3   petal_width           150 non-null    float64
 4   species               150 non-null    str
 5   sepal_area            150 non-null    float64
 6   petal_area            150 non-null    float64
 7   petal_to_sepal_ratio  150 non-null    float64
dtypes: float64(7), str(1)
memory usage: 9.5 KB

In [13]:
df_clean.shape

(150, 8)

In [14]:
df_clean.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'sepal_area', 'petal_area', 'petal_to_sepal_ratio'],
      dtype='str')